# Generated by Django 2.2.12 on 2021-03-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210309_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_trending',
            field=models.BooleanField(default=False),
        ),
    ]
